### ISSUE TITLE
Hey Would like help me in my mod

### ISSUE THREAD

**Issue by JeanTheFungle** [DaemonBeast/Mitochondria#8]
**hello @DaemonBeast i saw you api and i love it i know you are a good devs that why i contact you would like help me in some files**

[RegisterCustomRoleAttribute](https://github.com/Peasplayer/PeasAPI/blob/main/PeasAPI/Components/RegisterCustomRoleAttribute.cs)
[RegisterCustomGameModeAttribute](https://github.com/Peasplayer/PeasAPI/blob/main/PeasAPI/Components/RegisterCustomGameModeAttribute.cs)

i wante port thoses files to 2023.10.24 version of among us and thx 

if you see this answer me I'm waiting

**Comment by DaemonBeast** [comment]
Sorry but I'm unable to assist you with this particular situation. Perhaps you could open an issue on the repository the code you linked originates from: https://github.com/Peasplayer/PeasAPI/issues.
